# Generated by Django 2.0.5 on 2018-05-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Пользователа', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
